services:
    db:
        image: postgres:14.4-alpine
        hostname: db
        ports:
            - "5432:5432"
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=hexagonal_db
        restart: always
